sudo: true
language: python
python: 3.5
branches:
  only:
  - master
addons:
  apt:
    packages:
      - oracle-java8-set-default
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.1.deb && sudo dpkg -i --force-confnew elasticsearch-6.2.1.deb && sudo service elasticsearch start
install: bin/travis/install.sh
before_script:
  - bin/travis/lint.sh
  - bin/travis/setup.sh
script:
  - bin/travis/test.sh
